export const COUNTRIES = `Afghanistan|Aland Islands|Albania|Algeria|American Samoa|Andorra|Angola|Anguilla|Antarctica|Antigua and Barbuda|Argentina|Armenia|Aruba|Australia|Austria|Azerbaijan|Bahamas|Bahrain|Bangladesh|Barbados|Belarus|Belgium|Belize|Benin|Bermuda|Bhutan|Bolivia|Bonaire, Sint Eustatius and Saba|Bosnia and Herzegovina|Botswana|Bouvet Island|Brazil|British Indian Ocean Territory|Brunei|Bulgaria|Burkina Faso|Burundi|Cambodia|Cameroon|Canada|Cape Verde|Cayman Islands|Central African Republic|Chad|Chile|China|Christmas Island|Cocos (Keeling) Islands|Colombia|Comoros|Congo|Cook Islands|Costa Rica|Croatia|Cuba|Curacao|Cyprus|Czech Republic|Côte d'Ivoire|Denmark|Djibouti|Dominica|Dominican Republic|East Timor|Ecuador|Egypt|El Salvador|Equatorial Guinea|Eritrea|Estonia|Ethiopia|Falkland Islands (Malvinas)|Faroe Islands|Fiji|Finland|France|French Guiana|French Polynesia|French Southern Territories|Gabon|Gambia|Georgia|Germany|Ghana|Gibraltar|Greece|Greenland|Grenada|Guadeloupe|Guam|Guatemala|Guernsey|Guinea|Guinea-Bissau|Guyana|Haiti|Heard Island and McDonald Islands|Holy See|Honduras|Hong Kong|Hungary|Iceland|India|Indonesia|Iran|Iraq|Ireland|Isle of Man|Israel|Italy|Jamaica|Japan|Jersey|Jordan|Kazakhstan|Kenya|Kiribati|Kosovo|Kuwait|Kyrgyzstan|Laos|Latvia|Lebanon|Lesotho|Liberia|Libya|Liechtenstein|Lithuania|Luxembourg|Macao|Macedonia|Madagascar|Malawi|Malaysia|Maldives|Mali|Malta|Marshall Islands|Martinique|Mauritania|Mauritius|Mayotte|Mexico|Micronesia|Moldova|Monaco|Mongolia|Montenegro|Montserrat|Morocco|Mozambique|Myanmar|Namibia|Nauru|Nepal|Netherlands|New Caledonia|New Zealand|Nicaragua|Niger|Nigeria|Niue|Norfolk Island|North Korea|Northern Mariana Islands|Norway|Oman|Pakistan|Palau|Palestine|Panama|Papua New Guinea|Paraguay|Peru|Philippines|Pitcairn|Poland|Portugal|Puerto Rico|Qatar|Reunion|Romania|Russia|Rwanda|Saint Barthelemy|Saint Helena, Ascension and Tristan da Cunha|Saint Kitts and Nevis|Saint Lucia|Saint Martin (French part)|Saint Pierre and Miquelon|Saint Vincent and the Grenadines|Samoa|San Marino|Sao Tome and Principe|Saudi Arabia|Senegal|Serbia|Seychelles|Sierra Leone|Singapore|Sint Maarten (Dutch part)|Slovakia|Slovenia|Solomon Islands|Somalia|South Africa|South Georgia and the South Sandwich Islands|South Korea|South Sudan|Spain|Sri Lanka|Sudan|Suriname|Svalbard and Jan Mayen|Swaziland|Sweden|Switzerland|Syria|Taiwan|Tajikistan|Tanzania|Thailand|Timor-Leste|Togo|Tokelau|Tonga|Trinidad and Tobago|Tunisia|Turkey|Turkmenistan|Turks and Caicos Islands|Tuvalu|Uganda|Ukraine|United Arab Emirates|United Kingdom|United States|United States Minor Outlying Islands|Uruguay|Uzbekistan|Vanuatu|Vatican City|Venezuela|Vietnam|Virgin Islands, British|Virgin Islands, U.S.|Wallis and Futuna|Western Sahara|Yemen|Zambia|Zimbabwe`.split("|");

export const DIAL_CODES = {
  Afghanistan:"+93", Albania:"+355", Algeria:"+213", Andorra:"+376", Angola:"+244", Argentina:"+54", Armenia:"+374", Aruba:"+297", Australia:"+61", Austria:"+43", Azerbaijan:"+994",
  Bahamas:"+1242", Bahrain:"+973", Bangladesh:"+880", Barbados:"+1246", Belarus:"+375", Belgium:"+32", Belize:"+501", Benin:"+229", Bhutan:"+975", Bolivia:"+591", "Bosnia and Herzegovina":"+387", Botswana:"+267", Brazil:"+55", Brunei:"+673", Bulgaria:"+359", "Burkina Faso":"+226", Burundi:"+257",
  Cambodia:"+855", Cameroon:"+237", Canada:"+1", "Cape Verde":"+238", "Central African Republic":"+236", Chad:"+235", Chile:"+56", China:"+86", Colombia:"+57", Comoros:"+269", Congo:"+242", "Cook Islands":"+682", "Costa Rica":"+506", Croatia:"+385", Cuba:"+53", Cyprus:"+357", "Czech Republic":"+420", "Côte d'Ivoire":"+225",
  Denmark:"+45", Djibouti:"+253", Dominica:"+1767", "Dominican Republic":"+1809", Ecuador:"+593", Egypt:"+20", "El Salvador":"+503", "Equatorial Guinea":"+240", Eritrea:"+291", Estonia:"+372", Ethiopia:"+251",
  Fiji:"+679", Finland:"+358", France:"+33", Gabon:"+241", Gambia:"+220", Georgia:"+995", Germany:"+49", Ghana:"+233", Greece:"+30", Grenada:"+1473", Guatemala:"+502", Guinea:"+224", "Guinea-Bissau":"+245", Guyana:"+592",
  Haiti:"+509", Honduras:"+504", "Hong Kong":"+852", Hungary:"+36", Iceland:"+354", India:"+91", Indonesia:"+62", Iran:"+98", Iraq:"+964", Ireland:"+353", Israel:"+972", Italy:"+39", Jamaica:"+1876", Japan:"+81", Jordan:"+962",
  Kazakhstan:"+7", Kenya:"+254", Kiribati:"+686", Kosovo:"+383", Kuwait:"+965", Kyrgyzstan:"+996", Laos:"+856", Latvia:"+371", Lebanon:"+961", Lesotho:"+266", Liberia:"+231", Libya:"+218", Liechtenstein:"+423", Lithuania:"+370", Luxembourg:"+352",
  Macedonia:"+389", Madagascar:"+261", Malawi:"+265", Malaysia:"+60", Maldives:"+960", Mali:"+223", Malta:"+356", "Marshall Islands":"+692", Mauritania:"+222", Mauritius:"+230", Mexico:"+52", Micronesia:"+691", Moldova:"+373", Monaco:"+377", Mongolia:"+976", Montenegro:"+382", Morocco:"+212", Mozambique:"+258", Myanmar:"+95",
  Namibia:"+264", Nauru:"+674", Nepal:"+977", Netherlands:"+31", "New Zealand":"+64", Nicaragua:"+505", Niger:"+227", Nigeria:"+234", "North Korea":"+850", Norway:"+47", Oman:"+968", Pakistan:"+92", Palau:"+680", Palestine:"+970", Panama:"+507", "Papua New Guinea":"+675", Paraguay:"+595", Peru:"+51", Philippines:"+63", Poland:"+48", Portugal:"+351", Qatar:"+974",
  Romania:"+40", Russia:"+7", Rwanda:"+250", Samoa:"+685", "San Marino":"+378", "Sao Tome and Principe":"+239", "Saudi Arabia":"+966", Senegal:"+221", Serbia:"+381", Seychelles:"+248", "Sierra Leone":"+232", Singapore:"+65", Slovakia:"+421", Slovenia:"+386", "Solomon Islands":"+677", Somalia:"+252", "South Africa":"+27", "South Korea":"+82", "South Sudan":"+211", Spain:"+34", "Sri Lanka":"+94", Sudan:"+249", Suriname:"+597", Swaziland:"+268", Sweden:"+46", Switzerland:"+41", Syria:"+963",
  Taiwan:"+886", Tajikistan:"+992", Tanzania:"+255", Thailand:"+66", "Timor-Leste":"+670", "East Timor":"+670", Togo:"+228", Tonga:"+676", "Trinidad and Tobago":"+1868", Tunisia:"+216", Turkey:"+90", Turkmenistan:"+993", Tuvalu:"+688", Uganda:"+256", Ukraine:"+380", "United Arab Emirates":"+971", "United Kingdom":"+44", "United States":"+1", Uruguay:"+598", Uzbekistan:"+998", Vanuatu:"+678", "Vatican City":"+39", Venezuela:"+58", Vietnam:"+84", Yemen:"+967", Zambia:"+260", Zimbabwe:"+263"
};

Object.assign(DIAL_CODES, {
  "Aland Islands":"+358", "American Samoa":"+1684", Anguilla:"+1264", "Antigua and Barbuda":"+1268",
  Bermuda:"+1441", "Bonaire, Sint Eustatius and Saba":"+599", "British Indian Ocean Territory":"+246",
  "Cayman Islands":"+1345", "Christmas Island":"+61", "Cocos (Keeling) Islands":"+61", Curacao:"+599",
  "Falkland Islands (Malvinas)":"+500", "Faroe Islands":"+298", "French Guiana":"+594", "French Polynesia":"+689",
  Gibraltar:"+350", Greenland:"+299", Guadeloupe:"+590", Guam:"+1671", Guernsey:"+44", "Holy See":"+39",
  "Isle of Man":"+44", Jersey:"+44", Macao:"+853", Martinique:"+596", Mayotte:"+262", Montserrat:"+1664",
  "New Caledonia":"+687", Niue:"+683", "Norfolk Island":"+672", "Northern Mariana Islands":"+1670",
  Pitcairn:"+64", "Puerto Rico":"+1", Reunion:"+262", "Saint Barthelemy":"+590",
  "Saint Helena, Ascension and Tristan da Cunha":"+290", "Saint Kitts and Nevis":"+1869", "Saint Lucia":"+1758",
  "Saint Martin (French part)":"+590", "Saint Pierre and Miquelon":"+508", "Saint Vincent and the Grenadines":"+1784",
  "Sint Maarten (Dutch part)":"+1721", "South Georgia and the South Sandwich Islands":"+500",
  "Svalbard and Jan Mayen":"+47", Tokelau:"+690", "Turks and Caicos Islands":"+1649",
  "United States Minor Outlying Islands":"+1", "Virgin Islands, British":"+1284", "Virgin Islands, U.S.":"+1340",
  "Wallis and Futuna":"+681", "Western Sahara":"+212"
});
